apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"name":"local-hostpath-pvc","namespace":"default"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"5G"}},"storageClassName":"openebs-hostpath"}}
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: openebs.io/local
    volume.kubernetes.io/selected-node: minikube-4
  creationTimestamp: "2021-01-25T13:34:07Z"
  finalizers:
  - kubernetes.io/pvc-protection
  name: local-hostpath-pvc
  namespace: default
  resourceVersion: "163526546"
  selfLink: /api/v1/namespaces/default/persistentvolumeclaims/local-hostpath-pvc
  uid: 991022ee-ad78-4ac1-bf41-0cf70bee319e
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5G
  storageClassName: openebs-hostpath
  volumeMode: Filesystem
  volumeName: pvc-991022ee-ad78-4ac1-bf41-0cf70bee319e
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 5G
  phase: Bound
