apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: cstor.csi.openebs.io
  creationTimestamp: "2020-10-27T10:57:40Z"
  finalizers:
  - kubernetes.io/pv-protection
  - external-attacher/cstor-csi-openebs-io
  name: pvc-b84f60ae-3f26-4110-a85d-bce7ec00dacc
  resourceVersion: "104168221"
  selfLink: /api/v1/persistentvolumes/pvc-b84f60ae-3f26-4110-a85d-bce7ec00dacc
  uid: 0e8feed4-14ab-42d0-a69c-de2f34d0fd63
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 20Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: mongo
    namespace: default
    resourceVersion: "104168134"
    uid: b84f60ae-3f26-4110-a85d-bce7ec00dacc
  csi:
    driver: cstor.csi.openebs.io
    fsType: ext4
    volumeAttributes:
      openebs.io/cas-type: cstor
      storage.kubernetes.io/csiProvisionerIdentity: 1600839858463-8081-cstor.csi.openebs.io
    volumeHandle: pvc-b84f60ae-3f26-4110-a85d-bce7ec00dacc
  persistentVolumeReclaimPolicy: Delete
  storageClassName: common-storageclass
  volumeMode: Filesystem
status:
  phase: Bound
