apiVersion: cstor.openebs.io/v1
kind: CStorPoolInstance
metadata:
  creationTimestamp: "2020-06-09T16:03:26Z"
  finalizers:
  - cstorpoolcluster.openebs.io/finalizer
  - openebs.io/pool-protection
  generation: 45781
  labels:
    kubernetes.io/hostname: minikube-2
    openebs.io/cas-type: cstor
    openebs.io/cstor-pool-cluster: default-cstor-disk
    openebs.io/version: 2.1.0-ee
  name: default-cstor-disk-dcrm
  namespace: openebs
  ownerReferences:
  - apiVersion: cstor.openebs.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: CStorPoolCluster
    name: default-cstor-disk
    uid: ed126cc8-9473-4aa6-9e69-4d2ae8454a41
  resourceVersion: "227161140"
  selfLink: /apis/cstor.openebs.io/v1/namespaces/openebs/cstorpoolinstances/default-cstor-disk-dcrm
  uid: 3d661dd6-9c49-44bf-95ad-5efb44ad1622
spec:
  dataRaidGroups:
  - blockDevices:
    - blockDeviceName: blockdevice-c21bc3b79a98c7e8508f47558cc94f36
      devLink: /dev/disk/by-id/nvme-Amazon_Elastic_Block_Store_vol00a1730d6a6375fe3
  hostName: minikube-2
  nodeSelector:
    kubernetes.io/hostname: minikube-2
  poolConfig:
    compression: "off"
    dataRaidGroupType: stripe
    priorityClassName: ""
status:
  capacity:
    free: 77900M
    total: 96400M
    used: 18500M
    zfs:
      logicalUsed: 51800M
  conditions:
  - lastTransitionTime: "2020-07-30T05:43:47Z"
    lastUpdateTime: "2020-07-30T05:43:47Z"
    message: failed to importcstor-ed126cc8-9473-4aa6-9e69-4d2ae8454a41pool
    reason: PoolLost
    status: "True"
    type: PoolLost
  healthyReplicas: 7
  phase: ONLINE
  provisionedReplicas: 7
  readOnly: false
versionDetails:
  desired: 2.1.0-ee
  status:
    current: 2.1.0-ee
    dependentsUpgraded: true
    lastUpdateTime: "2020-11-03T10:07:42Z"
    state: Reconciled
