apiVersion: cstor.openebs.io/v1
kind: CStorPoolInstance
metadata:
  creationTimestamp: "2020-06-09T16:03:26Z"
  finalizers:
  - cstorpoolcluster.openebs.io/finalizer
  - openebs.io/pool-protection
  generation: 51257
  labels:
    kubernetes.io/hostname: minikube-1
    openebs.io/cas-type: cstor
    openebs.io/cstor-pool-cluster: default-cstor-disk
    openebs.io/version: 2.1.0-ee
  name: default-cstor-disk-fp6v
  namespace: openebs
  ownerReferences:
  - apiVersion: cstor.openebs.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: CStorPoolCluster
    name: default-cstor-disk
    uid: ed126cc8-9473-4aa6-9e69-4d2ae8454a41
  resourceVersion: "228448237"
  selfLink: /apis/cstor.openebs.io/v1/namespaces/openebs/cstorpoolinstances/default-cstor-disk-fp6v
  uid: c6dc25ca-6792-4767-b287-df1876ea83f7
spec:
  dataRaidGroups:
  - blockDevices:
    - blockDeviceName: blockdevice-8a5b69d8a2b23276f8daeac3c8179f9d
      devLink: /dev/disk/by-id/nvme-Amazon_Elastic_Block_Store_vol08a9d69fa93403a81
  hostName: minikube-1
  nodeSelector:
    kubernetes.io/hostname: minikube-1
  poolConfig:
    compression: "off"
    dataRaidGroupType: stripe
    priorityClassName: ""
status:
  capacity:
    free: 77900M
    total: 96400M
    used: 18500M
    zfs:
      logicalUsed: 51800M
  healthyReplicas: 7
  phase: ONLINE
  provisionedReplicas: 7
  readOnly: false
versionDetails:
  desired: 2.1.0-ee
  status:
    current: 2.1.0-ee
    dependentsUpgraded: true
    lastUpdateTime: "2020-11-02T18:45:53Z"
    state: Reconciled
